services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: lifedata
    ports:
      - "5437:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: