version: 2

models:
  - name: fct_cad_trips
    description: "Fact table for CAD trips"
    columns:
      - name: trip_leg_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: created_at
        description: "Timestamp when the trip leg was created"
      - name: modified_at
        description: "Timestamp when the trip leg was last modified"
      - name: _dbt_batch_id
        description: "Batch ID from DBT run"
      - name: _dbt_loaded_at
        description: "Timestamp when this record was loaded"