lan_dbt:
  target: prod
  outputs:
    prod:
      type: postgres
      host: warehouse
      user: "{{ env_var('WAREHOUSE_USER') }}"
      password: "{{ env_var('WAREHOUSE_PASS') }}"
      port: 5433
      dbname: warehouse
      threads: 8
      schema: analytics

