lan_dbt:
  target: dev
  outputs:
    prod:
      type: postgres
      host: warehouse
      user: "{{ env_var('WAREHOUSE_USER') }}"
      password: "{{ env_var('WAREHOUSE_PASS') }}"
      port: 5432
      dbname: warehouse
      threads: 8
      schema: staging
    dev:
      dbname: lifedata
      host: localhost
      pass: devpass
      port: 5437
      schema: staging
      threads: 1
      type: postgres
      user: user

