# .github/workflows/deploy-prefect.yml (for host-based runner)
name: Deploy Prefect Deployments

on:
  push:
    branches: [ master ]
    paths:
      - 'prefect.yaml'
      - 'flows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, prefect-deploy]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Prefect Server
      working-directory: /home/alex/pipeline  # Update this path
      run: |
        echo "Deploying Prefect configurations..."
        
        # Copy prefect.yaml and deploy using your existing CLI container
        docker compose run --rm -v "$GITHUB_WORKSPACE:/repo" cli -c "
          cp /repo/prefect.yaml ./prefect.yaml
          pwd
          ls -la
          echo 'Deploying from prefect.yaml...'
          prefect deploy --all
          ls -la
          echo '✅ Deployment completed!'
        "

    - name: Verify Deployment
      working-directory: /home/alex/pipeline  # Update this path
      run: |
        echo "Verifying deployments..."
        docker compose run --rm cli -c "
          echo 'Listing deployments:'
          prefect deployment ls
          echo '---'
          echo 'Listing work pools:'
          prefect work-pool ls
        "