# .github/workflows/deploy-prefect.yml (for host-based runner)
name: Deploy Prefect Deployments

on:
  push:
    branches: [ master ]
    paths:
      - 'prefect.yaml'
      - 'flows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, prefect-deploy]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create persistent secrets file
      run: |
        # Create secrets directory if it doesn't exist
        mkdir -p /home/alex/prefect-secrets
        
        # Create the secrets.toml file in a persistent location
        echo '${{ secrets.SECRETS_TOML }}' > /home/alex/prefect-secrets/secrets.toml
        
        chmod 600 /home/alex/prefect-secrets/secrets.toml