# .github/workflows/deploy-prefect.yml (for host-based runner)
name: Deploy Prefect Deployments

on:
  push:
    branches: [ master ]
    paths:
      - 'prefect.yaml'
      - 'flows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, prefect-deploy]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create environment file for secrets
      run: |
        # Create .env file that docker-compose will use
        cat > /home/alex/pipeline/.env << 'EOF'
        DLT_SECRETS_TOML=${{ secrets.SECRETS_TOML }}
        EOF
        chmod 600 /home/alex/pipeline/.env
        echo "Environment file created"

    - name: Deploy to Prefect Server
      working-directory: /home/alex/pipeline  # Update this path
      run: |
        export GITHUB_WORKSPACE=${{ github.workspace }}
        docker compose up -d
        echo "Deploying Prefect configurations..."
        docker compose run cli -c "
          pwd
          ls -la
          prefect deploy --all
          echo '✅ Deployment completed!'
        "

    - name: Verify Deployment
      working-directory: /home/alex/pipeline  # Update this path
      run: |
        echo "Verifying deployments..."
        docker compose run --rm cli -c "
          echo 'Listing deployments:'
          prefect deployment ls
          echo '---'
          echo 'Listing work pools:'
          prefect work-pool ls
        "