# .github/workflows/deploy-prefect.yml
name: Deploy Prefect Deployments

on:
  push:
    branches: [ master ]
    paths:
      - 'prefect.yaml'
      - 'flows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, prefect-deploy]  # Use your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Prefect Server
      run: |
        ls -a
        echo "Deploying Prefect configurations using CLI container..."
        
        # Change to the workspace directory where docker-compose.yaml is located
        cd /workspace
        
        # Copy prefect.yaml into the CLI container and run deployment
        docker compose --profile cli run --rm -v "$GITHUB_WORKSPACE:/repo" cli bash -c "
          echo 'Copying updated prefect.yaml...'
          cp /repo/prefect.yaml ./prefect.yaml
          
          echo 'Current working directory: \$(pwd)'
          echo 'Available files:'
          ls -la
          
          echo 'Checking prefect.yaml...'
          if [ -f prefect.yaml ]; then
            echo 'Found prefect.yaml, proceeding with deployment...'
            prefect deploy --all
            echo '✅ Deployment completed successfully!'
          else
            echo '❌ prefect.yaml not found!'
            exit 1
          fi
        "

    - name: Verify Deployment
      run: |
        echo "Verifying deployments..."
        cd /workspace
        docker compose --profile cli run --rm cli bash -c "
          echo 'Listing all deployments:'
          prefect deployment ls
          
          echo 'Checking work pools:'
          prefect work-pool ls
        "